[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"

[deploy]
startCommand = "node dist/server.js"
healthcheckPath = "/health"
healthcheckTimeout = 60
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 5
healthcheckInterval = 15

[[crons]]
schedule = "0 7 * * 1-5"
command = "node dist/index.js cron daily"

[[crons]]
schedule = "0 */4 * * *"
command = "node dist/index.js cron notify"

[[crons]]
schedule = "0 0 1 1 *"
command = "node dist/index.js cron holidays"